### ISSUE TITLE
Error Parsing MTI response

### ISSUE THREAD

**Issue by josedaudi** [alxnik/py8583#10] opened 2022-06-22 11:40 UTC
After receiving response from the socket, it fails to parse the message received.
`py8583.py8583.parseerror: 'invalid mti: [\x01$02]'`

**Comment by alxnik** [comment] 2022-06-23 11:34
Hello @josedaudi ,

The error signifies that the message you are receiving is invalid according to the library's rules. There might be an error in the message you are receiving or the iso8583 variant configuration you have set up the library with.

**Comment by josedaudi** [comment] 2022-06-23 11:52
The response I'm receiving is

`b'\x01$0210F23A40550AE0812C0000000016000020164839123456709012402010000000014300061702401520202902401506170617601212D00100000C0'`

When i try to parse it i get the error mentioned.

**Comment by alxnik** [comment] 2022-06-24 06:09
This is not a bug of the library so if you don't mind, I'll close this ticket.

**Closed as not planned by alxnik** 2022-06-24 06:09 UTC

**Comment by josedaudi** [comment] 2022-06-24 06:11
Okay, if you don't mind can you assist on how to parse the response above using the library
